W8D1/reddit_clone/config/routes.rb
Rails.application.routes.draw do


  # new create edit update destroy show
  
  resources :posts, except: [:index, :create, :new]

  resources :subs do
    resources :posts, only: [:create, :new]
  end

  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]

  resource :session, only: [:new, :create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

W8D1/reddit_clone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  url        :string           not null
#  content    :text             not null
#  sub_id     :integer          not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Post < ApplicationRecord
    #validations
    validates :title, :sub_id, :author_id, :content, presence: true
    validates :url, uniqueness: true

    #associations
    belongs_to :sub,
        primary_key: :id,
        foreign_key: :sub_id,
        class_name: :Sub

    belongs_to :author,
        primary_key: :id,
        foreign_key: :author_id,
        class_name: :User


end

W8D1/reddit_clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController


    def new
        @post = Post.new
        @post.sub_id = params[:sub_id]
        render :new
    end

    # Approach1: we can only use post_url(id) here in the controller
    # Approach2: assuming we can call post_url(id) anywhere, have some kidn of post-creation hook
    # in model

    def create
        @post = Post.new(posts_params)
        @post.sub_id = params[:sub_id]
        if @post.save
            @post.url = post_url(@post.id)
            redirect_to post_url(@post.id)
        else
            flash[:errors] = @post.errors.full_messages
            render :new
        end
    end

    def edit
        @post = Post.find(params[:id])
        render :edit
    end

    def update
    end

    def destroy
    end

    def show
        @post = Post.find(params[:id])
        render :show
    end

    private
    def posts_params
        params.require(:post).permit(:title, :author_id, :content)
    end
end

W8D1/reddit_clone/app/helpers/posts_helper.rb
module PostsHelper
end

W8D1/reddit_clone/app/views/posts/new.html.erb
<div>
    <form action="<%= sub_posts_url(@post.sub_id) %>" method="POST">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="hidden" name="post[author_id]" value="<%= current_user.id %>">

        <label>Title
            <input type="text" name="post[title]">
        </label>
        <label>Content
            <textarea name="post[content" cols="30" rows="10"></textarea>
        </label>
        <input type="submit" value="Create Post">
    </form>
</div>

W8D1/reddit_clone/app/views/posts/show.html.erb
<h1>Post</h1>
<p>
    <%= @post.title %>
</p>
<p>
    <%= @post.content %>
</p>
<p>
    <%= @post.author.username %>
</p>
<p>
    <%= @post.sub.title %>
</p>